/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AssicurazioneVeicoli {
    }
    interface BannerApp {
    }
    interface BannerCertezze {
    }
    interface BcgHeader {
    }
    interface BottomFooter {
    }
    interface ContactForm {
    }
    interface FetchArticoli {
    }
    interface FirstContent {
    }
    interface FormWrapper {
    }
    interface HeaderEffetto {
    }
    interface TopNavbar {
    }
    interface TxtHeader {
    }
    interface WebsiteContainer {
    }
}
declare global {
    interface HTMLAssicurazioneVeicoliElement extends Components.AssicurazioneVeicoli, HTMLStencilElement {
    }
    var HTMLAssicurazioneVeicoliElement: {
        prototype: HTMLAssicurazioneVeicoliElement;
        new (): HTMLAssicurazioneVeicoliElement;
    };
    interface HTMLBannerAppElement extends Components.BannerApp, HTMLStencilElement {
    }
    var HTMLBannerAppElement: {
        prototype: HTMLBannerAppElement;
        new (): HTMLBannerAppElement;
    };
    interface HTMLBannerCertezzeElement extends Components.BannerCertezze, HTMLStencilElement {
    }
    var HTMLBannerCertezzeElement: {
        prototype: HTMLBannerCertezzeElement;
        new (): HTMLBannerCertezzeElement;
    };
    interface HTMLBcgHeaderElement extends Components.BcgHeader, HTMLStencilElement {
    }
    var HTMLBcgHeaderElement: {
        prototype: HTMLBcgHeaderElement;
        new (): HTMLBcgHeaderElement;
    };
    interface HTMLBottomFooterElement extends Components.BottomFooter, HTMLStencilElement {
    }
    var HTMLBottomFooterElement: {
        prototype: HTMLBottomFooterElement;
        new (): HTMLBottomFooterElement;
    };
    interface HTMLContactFormElement extends Components.ContactForm, HTMLStencilElement {
    }
    var HTMLContactFormElement: {
        prototype: HTMLContactFormElement;
        new (): HTMLContactFormElement;
    };
    interface HTMLFetchArticoliElement extends Components.FetchArticoli, HTMLStencilElement {
    }
    var HTMLFetchArticoliElement: {
        prototype: HTMLFetchArticoliElement;
        new (): HTMLFetchArticoliElement;
    };
    interface HTMLFirstContentElement extends Components.FirstContent, HTMLStencilElement {
    }
    var HTMLFirstContentElement: {
        prototype: HTMLFirstContentElement;
        new (): HTMLFirstContentElement;
    };
    interface HTMLFormWrapperElement extends Components.FormWrapper, HTMLStencilElement {
    }
    var HTMLFormWrapperElement: {
        prototype: HTMLFormWrapperElement;
        new (): HTMLFormWrapperElement;
    };
    interface HTMLHeaderEffettoElement extends Components.HeaderEffetto, HTMLStencilElement {
    }
    var HTMLHeaderEffettoElement: {
        prototype: HTMLHeaderEffettoElement;
        new (): HTMLHeaderEffettoElement;
    };
    interface HTMLTopNavbarElement extends Components.TopNavbar, HTMLStencilElement {
    }
    var HTMLTopNavbarElement: {
        prototype: HTMLTopNavbarElement;
        new (): HTMLTopNavbarElement;
    };
    interface HTMLTxtHeaderElement extends Components.TxtHeader, HTMLStencilElement {
    }
    var HTMLTxtHeaderElement: {
        prototype: HTMLTxtHeaderElement;
        new (): HTMLTxtHeaderElement;
    };
    interface HTMLWebsiteContainerElement extends Components.WebsiteContainer, HTMLStencilElement {
    }
    var HTMLWebsiteContainerElement: {
        prototype: HTMLWebsiteContainerElement;
        new (): HTMLWebsiteContainerElement;
    };
    interface HTMLElementTagNameMap {
        "assicurazione-veicoli": HTMLAssicurazioneVeicoliElement;
        "banner-app": HTMLBannerAppElement;
        "banner-certezze": HTMLBannerCertezzeElement;
        "bcg-header": HTMLBcgHeaderElement;
        "bottom-footer": HTMLBottomFooterElement;
        "contact-form": HTMLContactFormElement;
        "fetch-articoli": HTMLFetchArticoliElement;
        "first-content": HTMLFirstContentElement;
        "form-wrapper": HTMLFormWrapperElement;
        "header-effetto": HTMLHeaderEffettoElement;
        "top-navbar": HTMLTopNavbarElement;
        "txt-header": HTMLTxtHeaderElement;
        "website-container": HTMLWebsiteContainerElement;
    }
}
declare namespace LocalJSX {
    interface AssicurazioneVeicoli {
    }
    interface BannerApp {
    }
    interface BannerCertezze {
    }
    interface BcgHeader {
    }
    interface BottomFooter {
    }
    interface ContactForm {
    }
    interface FetchArticoli {
    }
    interface FirstContent {
    }
    interface FormWrapper {
    }
    interface HeaderEffetto {
    }
    interface TopNavbar {
    }
    interface TxtHeader {
    }
    interface WebsiteContainer {
    }
    interface IntrinsicElements {
        "assicurazione-veicoli": AssicurazioneVeicoli;
        "banner-app": BannerApp;
        "banner-certezze": BannerCertezze;
        "bcg-header": BcgHeader;
        "bottom-footer": BottomFooter;
        "contact-form": ContactForm;
        "fetch-articoli": FetchArticoli;
        "first-content": FirstContent;
        "form-wrapper": FormWrapper;
        "header-effetto": HeaderEffetto;
        "top-navbar": TopNavbar;
        "txt-header": TxtHeader;
        "website-container": WebsiteContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "assicurazione-veicoli": LocalJSX.AssicurazioneVeicoli & JSXBase.HTMLAttributes<HTMLAssicurazioneVeicoliElement>;
            "banner-app": LocalJSX.BannerApp & JSXBase.HTMLAttributes<HTMLBannerAppElement>;
            "banner-certezze": LocalJSX.BannerCertezze & JSXBase.HTMLAttributes<HTMLBannerCertezzeElement>;
            "bcg-header": LocalJSX.BcgHeader & JSXBase.HTMLAttributes<HTMLBcgHeaderElement>;
            "bottom-footer": LocalJSX.BottomFooter & JSXBase.HTMLAttributes<HTMLBottomFooterElement>;
            "contact-form": LocalJSX.ContactForm & JSXBase.HTMLAttributes<HTMLContactFormElement>;
            "fetch-articoli": LocalJSX.FetchArticoli & JSXBase.HTMLAttributes<HTMLFetchArticoliElement>;
            "first-content": LocalJSX.FirstContent & JSXBase.HTMLAttributes<HTMLFirstContentElement>;
            "form-wrapper": LocalJSX.FormWrapper & JSXBase.HTMLAttributes<HTMLFormWrapperElement>;
            "header-effetto": LocalJSX.HeaderEffetto & JSXBase.HTMLAttributes<HTMLHeaderEffettoElement>;
            "top-navbar": LocalJSX.TopNavbar & JSXBase.HTMLAttributes<HTMLTopNavbarElement>;
            "txt-header": LocalJSX.TxtHeader & JSXBase.HTMLAttributes<HTMLTxtHeaderElement>;
            "website-container": LocalJSX.WebsiteContainer & JSXBase.HTMLAttributes<HTMLWebsiteContainerElement>;
        }
    }
}
