/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BcgHeader {
    }
    interface BlobImg {
    }
    interface BottomFooter {
    }
    interface ContactForm {
    }
    interface FetchArticoli {
    }
    interface FormWrapper {
    }
    interface TopNavbar {
    }
    interface TxtHeader {
    }
}
declare global {
    interface HTMLBcgHeaderElement extends Components.BcgHeader, HTMLStencilElement {
    }
    var HTMLBcgHeaderElement: {
        prototype: HTMLBcgHeaderElement;
        new (): HTMLBcgHeaderElement;
    };
    interface HTMLBlobImgElement extends Components.BlobImg, HTMLStencilElement {
    }
    var HTMLBlobImgElement: {
        prototype: HTMLBlobImgElement;
        new (): HTMLBlobImgElement;
    };
    interface HTMLBottomFooterElement extends Components.BottomFooter, HTMLStencilElement {
    }
    var HTMLBottomFooterElement: {
        prototype: HTMLBottomFooterElement;
        new (): HTMLBottomFooterElement;
    };
    interface HTMLContactFormElement extends Components.ContactForm, HTMLStencilElement {
    }
    var HTMLContactFormElement: {
        prototype: HTMLContactFormElement;
        new (): HTMLContactFormElement;
    };
    interface HTMLFetchArticoliElement extends Components.FetchArticoli, HTMLStencilElement {
    }
    var HTMLFetchArticoliElement: {
        prototype: HTMLFetchArticoliElement;
        new (): HTMLFetchArticoliElement;
    };
    interface HTMLFormWrapperElement extends Components.FormWrapper, HTMLStencilElement {
    }
    var HTMLFormWrapperElement: {
        prototype: HTMLFormWrapperElement;
        new (): HTMLFormWrapperElement;
    };
    interface HTMLTopNavbarElement extends Components.TopNavbar, HTMLStencilElement {
    }
    var HTMLTopNavbarElement: {
        prototype: HTMLTopNavbarElement;
        new (): HTMLTopNavbarElement;
    };
    interface HTMLTxtHeaderElement extends Components.TxtHeader, HTMLStencilElement {
    }
    var HTMLTxtHeaderElement: {
        prototype: HTMLTxtHeaderElement;
        new (): HTMLTxtHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "bcg-header": HTMLBcgHeaderElement;
        "blob-img": HTMLBlobImgElement;
        "bottom-footer": HTMLBottomFooterElement;
        "contact-form": HTMLContactFormElement;
        "fetch-articoli": HTMLFetchArticoliElement;
        "form-wrapper": HTMLFormWrapperElement;
        "top-navbar": HTMLTopNavbarElement;
        "txt-header": HTMLTxtHeaderElement;
    }
}
declare namespace LocalJSX {
    interface BcgHeader {
    }
    interface BlobImg {
    }
    interface BottomFooter {
    }
    interface ContactForm {
    }
    interface FetchArticoli {
    }
    interface FormWrapper {
    }
    interface TopNavbar {
    }
    interface TxtHeader {
    }
    interface IntrinsicElements {
        "bcg-header": BcgHeader;
        "blob-img": BlobImg;
        "bottom-footer": BottomFooter;
        "contact-form": ContactForm;
        "fetch-articoli": FetchArticoli;
        "form-wrapper": FormWrapper;
        "top-navbar": TopNavbar;
        "txt-header": TxtHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bcg-header": LocalJSX.BcgHeader & JSXBase.HTMLAttributes<HTMLBcgHeaderElement>;
            "blob-img": LocalJSX.BlobImg & JSXBase.HTMLAttributes<HTMLBlobImgElement>;
            "bottom-footer": LocalJSX.BottomFooter & JSXBase.HTMLAttributes<HTMLBottomFooterElement>;
            "contact-form": LocalJSX.ContactForm & JSXBase.HTMLAttributes<HTMLContactFormElement>;
            "fetch-articoli": LocalJSX.FetchArticoli & JSXBase.HTMLAttributes<HTMLFetchArticoliElement>;
            "form-wrapper": LocalJSX.FormWrapper & JSXBase.HTMLAttributes<HTMLFormWrapperElement>;
            "top-navbar": LocalJSX.TopNavbar & JSXBase.HTMLAttributes<HTMLTopNavbarElement>;
            "txt-header": LocalJSX.TxtHeader & JSXBase.HTMLAttributes<HTMLTxtHeaderElement>;
        }
    }
}
