/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AssicurazioneVeicoli {
    }
    interface BannerApp {
    }
    interface BannerCertezze {
    }
    interface BcgHeader {
    interface BottomFooter {
    }
    interface CarCard {
    }
    interface ContactForm {
    }
    interface ContenitoreFlex {
    }
    interface FetchArticoli {
    }
    interface BlobImg {
    }
    interface ContentFeatures {
    }
    interface FetchSample {
    }
    interface FormWrapper {
    }
    interface MiniCard {
        "continua": string;
        "spiegazione": string;
        "titoletto": string;
    }
    interface NamedSlotParagraph {
    }
    interface SlotParagraph {
    }
    interface TopNavbar {
    }
    interface TravelCard {
    }
    interface TxtHeader {
    }
}
declare global {
    interface HTMLAssicurazioneVeicoliElement extends Components.AssicurazioneVeicoli, HTMLStencilElement {
    }
    var HTMLAssicurazioneVeicoliElement: {
        prototype: HTMLAssicurazioneVeicoliElement;
        new (): HTMLAssicurazioneVeicoliElement;
    };
    interface HTMLBannerAppElement extends Components.BannerApp, HTMLStencilElement {
    }
    var HTMLBannerAppElement: {
        prototype: HTMLBannerAppElement;
        new (): HTMLBannerAppElement;
    };
    interface HTMLBannerCertezzeElement extends Components.BannerCertezze, HTMLStencilElement {
    }
    var HTMLBannerCertezzeElement: {
        prototype: HTMLBannerCertezzeElement;
        new (): HTMLBannerCertezzeElement;
    };
    interface HTMLBcgHeaderElement extends Components.BcgHeader, HTMLStencilElement {
    }
    var HTMLBcgHeaderElement: {
        prototype: HTMLBcgHeaderElement;
        new (): HTMLBcgHeaderElement;
    };
    interface HTMLBlobImgElement extends Components.BlobImg, HTMLStencilElement {
    }
    var HTMLBlobImgElement: {
        prototype: HTMLBlobImgElement;
        new (): HTMLBlobImgElement;
    };
    interface HTMLContentFeaturesElement extends Components.ContentFeatures, HTMLStencilElement {
    }
    var HTMLContentFeaturesElement: {
        prototype: HTMLContentFeaturesElement;
        new (): HTMLContentFeaturesElement;
    };
    interface HTMLFetchSampleElement extends Components.FetchSample, HTMLStencilElement {
    }
    var HTMLFetchSampleElement: {
        prototype: HTMLFetchSampleElement;
        new (): HTMLFetchSampleElement;
    interface HTMLBottomFooterElement extends Components.BottomFooter, HTMLStencilElement {
    }
    var HTMLBottomFooterElement: {
        prototype: HTMLBottomFooterElement;
        new (): HTMLBottomFooterElement;
    };
    interface HTMLCarCardElement extends Components.CarCard, HTMLStencilElement {
    }
    var HTMLCarCardElement: {
        prototype: HTMLCarCardElement;
        new (): HTMLCarCardElement;
    };
    interface HTMLContactFormElement extends Components.ContactForm, HTMLStencilElement {
    }
    var HTMLContactFormElement: {
        prototype: HTMLContactFormElement;
        new (): HTMLContactFormElement;
    };
    interface HTMLContenitoreFlexElement extends Components.ContenitoreFlex, HTMLStencilElement {
    }
    var HTMLContenitoreFlexElement: {
        prototype: HTMLContenitoreFlexElement;
        new (): HTMLContenitoreFlexElement;
    };
    interface HTMLFetchArticoliElement extends Components.FetchArticoli, HTMLStencilElement {
    }
    var HTMLFetchArticoliElement: {
        prototype: HTMLFetchArticoliElement;
        new (): HTMLFetchArticoliElement;
    };
    interface HTMLFormWrapperElement extends Components.FormWrapper, HTMLStencilElement {
    }
    var HTMLFormWrapperElement: {
        prototype: HTMLFormWrapperElement;
        new (): HTMLFormWrapperElement;
    };
    interface HTMLMiniCardElement extends Components.MiniCard, HTMLStencilElement {
    }
    var HTMLMiniCardElement: {
        prototype: HTMLMiniCardElement;
        new (): HTMLMiniCardElement;
    };
    interface HTMLNamedSlotParagraphElement extends Components.NamedSlotParagraph, HTMLStencilElement {
    }
    var HTMLNamedSlotParagraphElement: {
        prototype: HTMLNamedSlotParagraphElement;
        new (): HTMLNamedSlotParagraphElement;
    };
    interface HTMLSlotParagraphElement extends Components.SlotParagraph, HTMLStencilElement {
    }
    var HTMLSlotParagraphElement: {
        prototype: HTMLSlotParagraphElement;
        new (): HTMLSlotParagraphElement;
    };
    interface HTMLTopNavbarElement extends Components.TopNavbar, HTMLStencilElement {
    }
    var HTMLTopNavbarElement: {
        prototype: HTMLTopNavbarElement;
        new (): HTMLTopNavbarElement;
    };
    interface HTMLTravelCardElement extends Components.TravelCard, HTMLStencilElement {
    }
    var HTMLTravelCardElement: {
        prototype: HTMLTravelCardElement;
        new (): HTMLTravelCardElement;
    };
    interface HTMLTxtHeaderElement extends Components.TxtHeader, HTMLStencilElement {
    }
    var HTMLTxtHeaderElement: {
        prototype: HTMLTxtHeaderElement;
        new (): HTMLTxtHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "assicurazione-veicoli": HTMLAssicurazioneVeicoliElement;
        "banner-app": HTMLBannerAppElement;
        "banner-certezze": HTMLBannerCertezzeElement;
        "bcg-header": HTMLBcgHeaderElement;
        "blob-img": HTMLBlobImgElement;
        "content-features": HTMLContentFeaturesElement;
        "fetch-sample": HTMLFetchSampleElement;
        "bottom-footer": HTMLBottomFooterElement;
        "car-card": HTMLCarCardElement;
        "contact-form": HTMLContactFormElement;
        "contenitore-flex": HTMLContenitoreFlexElement;
        "fetch-articoli": HTMLFetchArticoliElement;
        "form-wrapper": HTMLFormWrapperElement;
        "mini-card": HTMLMiniCardElement;
        "named-slot-paragraph": HTMLNamedSlotParagraphElement;
        "slot-paragraph": HTMLSlotParagraphElement;
        "top-navbar": HTMLTopNavbarElement;
        "txt-header": HTMLTxtHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AssicurazioneVeicoli {
    }
    interface BannerApp {
    }
    interface BannerCertezze {
    }
    interface BcgHeader {
    interface BottomFooter {
    }
    interface CarCard {
    }
    interface ContactForm {
    }
    interface ContenitoreFlex {
    }
    interface FetchArticoli {
    }
    interface BlobImg {
    }
    interface ContentFeatures {
    }
    interface FetchSample {
    }
    interface FormWrapper {
    }
    interface MiniCard {
        "continua"?: string;
        "spiegazione"?: string;
        "titoletto"?: string;
    }
    interface NamedSlotParagraph {
    }
    interface SlotParagraph {
    }
    interface TopNavbar {
    }
    interface TravelCard {
    }
    interface TxtHeader {
    }
    interface IntrinsicElements {
        "assicurazione-veicoli": AssicurazioneVeicoli;
        "banner-app": BannerApp;
        "banner-certezze": BannerCertezze;
        "bcg-header": BcgHeader;
        "blob-img": BlobImg;
        "content-features": ContentFeatures;
        "fetch-sample": FetchSample;
        "bottom-footer": BottomFooter;
        "car-card": CarCard;
        "contact-form": ContactForm;
        "contenitore-flex": ContenitoreFlex;
        "fetch-articoli": FetchArticoli;
        "form-wrapper": FormWrapper;
        "mini-card": MiniCard;
        "named-slot-paragraph": NamedSlotParagraph;
        "slot-paragraph": SlotParagraph;
        "top-navbar": TopNavbar;
        "travel-card": TravelCard;
        "txt-header": TxtHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "assicurazione-veicoli": LocalJSX.AssicurazioneVeicoli & JSXBase.HTMLAttributes<HTMLAssicurazioneVeicoliElement>;
            "banner-app": LocalJSX.BannerApp & JSXBase.HTMLAttributes<HTMLBannerAppElement>;
            "banner-certezze": LocalJSX.BannerCertezze & JSXBase.HTMLAttributes<HTMLBannerCertezzeElement>;
            "bcg-header": LocalJSX.BcgHeader & JSXBase.HTMLAttributes<HTMLBcgHeaderElement>;
            "blob-img": LocalJSX.BlobImg & JSXBase.HTMLAttributes<HTMLBlobImgElement>;
            "content-features": LocalJSX.ContentFeatures & JSXBase.HTMLAttributes<HTMLContentFeaturesElement>;
            "fetch-sample": LocalJSX.FetchSample & JSXBase.HTMLAttributes<HTMLFetchSampleElement>;
            "bottom-footer": LocalJSX.BottomFooter & JSXBase.HTMLAttributes<HTMLBottomFooterElement>;
            "car-card": LocalJSX.CarCard & JSXBase.HTMLAttributes<HTMLCarCardElement>;
            "contact-form": LocalJSX.ContactForm & JSXBase.HTMLAttributes<HTMLContactFormElement>;
            "contenitore-flex": LocalJSX.ContenitoreFlex & JSXBase.HTMLAttributes<HTMLContenitoreFlexElement>;
            "fetch-articoli": LocalJSX.FetchArticoli & JSXBase.HTMLAttributes<HTMLFetchArticoliElement>;
            "form-wrapper": LocalJSX.FormWrapper & JSXBase.HTMLAttributes<HTMLFormWrapperElement>;
            "mini-card": LocalJSX.MiniCard & JSXBase.HTMLAttributes<HTMLMiniCardElement>;
            "named-slot-paragraph": LocalJSX.NamedSlotParagraph & JSXBase.HTMLAttributes<HTMLNamedSlotParagraphElement>;
            "slot-paragraph": LocalJSX.SlotParagraph & JSXBase.HTMLAttributes<HTMLSlotParagraphElement>;
            "top-navbar": LocalJSX.TopNavbar & JSXBase.HTMLAttributes<HTMLTopNavbarElement>;
            "travel-card": LocalJSX.TravelCard & JSXBase.HTMLAttributes<HTMLTravelCardElement>;
            "txt-header": LocalJSX.TxtHeader & JSXBase.HTMLAttributes<HTMLTxtHeaderElement>;
        }
    }
}
